repos:
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args:
            - --line-length=80
              # these folders wont be formatted by black
            - --exclude="""\.git |
              \.__pycache__|
              \.hg|
              \.mypy_cache|
              \.tox|
              \.venv|
              _build|
              buck-out|
              build|
              dist|
              docs|
              tests"""
            - --force-exclude="""tests/"""

        additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args:
            - "--max-line-length=80"
            - "--max-complexity=10"
            - "--ignore=F401,W503,C901"
